const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

const MY_ORDER_REQUEST = "MY_ORDER_REQUEST";
const MY_ORDER_SUCCESS = "MY_ORDER_SUCCESS";
const MY_ORDER_FAIL = "MY_ORDER_FAIL";

const ORDER_DETAIL_REQUEST = "ORDER_DETAIL_REQUEST";
const ORDER_DETAIL_SUCCESS = "ORDER_DETAIL_SUCCESS";
const ORDER_DETAIL_FAIL = "ORDER_DETAIL_FAIL";

const CLEAR_ERROR = "CLEAR_ERROR";

export {
  CREATE_ORDER_REQUEST,
  CREATE_ORDER_SUCCESS,
  CREATE_ORDER_FAIL,

  MY_ORDER_REQUEST,
  MY_ORDER_SUCCESS,
  MY_ORDER_FAIL,

  ORDER_DETAIL_REQUEST,
  ORDER_DETAIL_SUCCESS,
  ORDER_DETAIL_FAIL,

  CLEAR_ERROR,
}
