const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST"
const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS"
const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL"

const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST"
const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS"
const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL"

const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST"
const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS"
const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL"
const NEW_REVIEW_RESET = "NEW_REVIEW_RESET"

const CLEAR_ERRORS = "CLEAR_ERRORS"

export {
  ALL_PRODUCT_REQUEST,
  ALL_PRODUCT_FAIL,
  ALL_PRODUCT_SUCCESS,

  PRODUCT_DETAIL_REQUEST,
  PRODUCT_DETAIL_FAIL,
  PRODUCT_DETAIL_SUCCESS,

  NEW_REVIEW_REQUEST,
  NEW_REVIEW_SUCCESS,
  NEW_REVIEW_FAIL,
  NEW_REVIEW_RESET,

  CLEAR_ERRORS,
}
