const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST"
const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS"
const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL"

const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST"
const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS"
const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL"

const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST"
const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS"
const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL"
const NEW_REVIEW_RESET = "NEW_REVIEW_RESET"

const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST"
const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS"
const ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL"

const NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST"
const NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS"
const NEW_PRODUCT_FAIL = "NEW_PRODUCT_FAIL"
const NEW_PRODUCT_RESET = "NEW_PRODUCT_RESET"

const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST"
const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL"
const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET"

const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST"
const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"
const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL"
const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET"

const CLEAR_ERRORS = "CLEAR_ERRORS"

export {
  ALL_PRODUCT_REQUEST,
  ALL_PRODUCT_FAIL,
  ALL_PRODUCT_SUCCESS,

  PRODUCT_DETAIL_REQUEST,
  PRODUCT_DETAIL_FAIL,
  PRODUCT_DETAIL_SUCCESS,

  NEW_REVIEW_REQUEST,
  NEW_REVIEW_SUCCESS,
  NEW_REVIEW_FAIL,
  NEW_REVIEW_RESET,

  ADMIN_PRODUCT_REQUEST,
  ADMIN_PRODUCT_SUCCESS,
  ADMIN_PRODUCT_FAIL,

  NEW_PRODUCT_REQUEST,
  NEW_PRODUCT_SUCCESS,
  NEW_PRODUCT_FAIL,
  NEW_PRODUCT_RESET,

  DELETE_PRODUCT_REQUEST,
  DELETE_PRODUCT_SUCCESS,
  DELETE_PRODUCT_FAIL,
  DELETE_PRODUCT_RESET,

  UPDATE_PRODUCT_REQUEST,
  UPDATE_PRODUCT_SUCCESS,
  UPDATE_PRODUCT_FAIL,
  UPDATE_PRODUCT_RESET,

  CLEAR_ERRORS,
}
