const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST"
const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS"
const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL"

const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST"
const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS"
const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL"

const CLEAR_ERRORS = "CLEAR_ERRORS"

export {
  ALL_PRODUCT_REQUEST,
  ALL_PRODUCT_FAIL,
  ALL_PRODUCT_SUCCESS,

  PRODUCT_DETAIL_REQUEST,
  PRODUCT_DETAIL_FAIL,
  PRODUCT_DETAIL_SUCCESS,
  CLEAR_ERRORS,
}
