const LOGIN_REQUEST = "LOGIN_REQUEST"
const LOGIN_SUCCESS = "LOGIN_SUCCESS"
const LOGIN_FAIL = "LOGIN_FAIL"

const REGISTER_REQUEST = "REGISTER_REQUEST"
const REGISTER_SUCCESS = "REGISTER_SUCCESS"
const REGISTER_FAIL = "REGISTER_FAIL"

const LOAD_USER_REQUEST = "LOAD_USER_REQUEST"
const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS"
const LOAD_USER_FAIL = "LOAD_USER_FAIL"

const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST"
const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"
const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET"
const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL"

const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST"
const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS"
const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET"
const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL"

const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST"
const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS"
const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL"

const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
const LOGOUT_FAIL = "LOGOUT_FAIL"

const CLEAR_ERRORS = "CLEAR_ERRORS"

export {
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAIL,

  REGISTER_REQUEST,
  REGISTER_SUCCESS,
  REGISTER_FAIL,

  LOAD_USER_REQUEST,
  LOAD_USER_SUCCESS,
  LOAD_USER_FAIL,

  UPDATE_PROFILE_REQUEST,
  UPDATE_PROFILE_SUCCESS,
  UPDATE_PROFILE_RESET,
  UPDATE_PROFILE_FAIL,

  UPDATE_PASSWORD_REQUEST,
  UPDATE_PASSWORD_SUCCESS,
  UPDATE_PASSWORD_RESET,
  UPDATE_PASSWORD_FAIL,

  FORGOT_PASSWORD_REQUEST,
  FORGOT_PASSWORD_SUCCESS,
  FORGOT_PASSWORD_FAIL,

  LOGOUT_SUCCESS,
  LOGOUT_FAIL,

  CLEAR_ERRORS,
}
